sudo: required
dist: trusty

branches:
    except:
        - l10n_develop

language: cpp

compiler: gcc

env:
    global:
        secure: "C4tE5UQtoItWxd+sSfj9vULLd0EjY5Ek/BentI/m1xz6tAOi+65RTjMEgz9OQZh1rlsExV4y9YEfV/JzZ3peLNypw3b2BaCum6LECkaEDob2aPR03u/DruTkGkXITUIFFh2hg0iQH2TZP9/0ZtQBRXqNbU+DnH8Rs1Q+kNcWoFU="

addons:
    coverity_scan:
        project:
            name: "rakhimov/scram"
        # description: "Command-line Risk Analysis Multi-tool"
        notification_email: "ol.rakhimov@gmail.com"
        build_command_prepend: "cmake .."
        build_command: "make -j 2"
        branch_pattern: "coverity-scan"
    apt:
        packages:
            - gcc-4.9
            - g++-4.9
            - libxml2-dev
            - libgoogle-perftools-dev
            - qtbase5-dev
            - qtbase5-dev-tools
            - qttools5-dev
            - qttools5-dev-tools
            - libqt5svg5-dev
            - libqt5opengl5-dev
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:kzemek/boost"

before_install:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
    - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] has been found, exiting."
      && exit 0 || echo "continue"

install:
    - .travis/install.sh  # Dependencies are built with gcc or clang.

before_script:
    - find src/ tests/ -type f | grep -v 'error' | xargs -n 1 sed -i 's/noexcept//'
    - mkdir build
    - cd build

script:
    - echo "Done"

after_success:
    - cat cov-int/scm_log.txt

after_failure:
    - cat cov-int/build-log.txt
